[flyway]
locations = ["filesystem:sql"]      # Locations of SQL Scripts
baselineOnMigrate = true            # Set to true if the database already exists
baselineVersion = "0"               # The version to start tracking from
validateOnMigrate = true            # Ensure migration scripts haven't been modified
cleanDisabled = true                # Prevent accidental database wipe
outOfOrder = false                  # Prevent applying migrations out of sequence
reportEnabled = true                # report migration status
sqlMigrationPrefix = "V"            # Prefix for versioned migrations
repeatableSqlMigrationPrefix = "R"  # Prefix for repeatable migrations
sqlMigrationSeparator = "__"        # Separator between version and description
sqlMigrationSuffixes = [".sql"]     # Migration file suffixes
outputQueryResults = true           # Show results of SQL statements