services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root # change this
      POSTGRES_PASSWORD: root # change this
      POSTGRES_DB: mydatabase
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com # change this
      PGADMIN_DEFAULT_PASSWORD: root # change this
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  flyway:
    image: flyway/flyway
    container_name: flyway_migrations
    depends_on:
      - db
    volumes:
      - ../sql:/flyway/sql
    command: [
      "migrate",
      "-url=jdbc:postgresql://db:5432/mydatabase",
      "-user=root",
      "-password=root",
      "-validateMigrationNaming=true"
    ]

volumes:
  local_pgdata:
  pgadmin-data: