BEGIN TRANSACTION;

DROP ROLE IF EXISTS app_user;
DROP ROLE IF EXISTS backup_operator;
DROP ROLE IF EXISTS developer;
DROP ROLE IF EXISTS editor;
DROP ROLE IF EXISTS reader;
DROP ROLE IF EXISTS admin;

COMMIT;