CALL magic_beans_schema.add_magical_property('Invisibility', 'Grants temporary invisibility to the user');
CALL magic_beans_schema.add_magical_property('Teleportation', 'Allows instant travel to a known location');
CALL magic_beans_schema.add_magical_property('Fireproof', 'Makes the user immune to fire');
CALL magic_beans_schema.add_magical_property('Water Breathing', 'Enables breathing underwater');
CALL magic_beans_schema.add_magical_property('Super Strength', 'Temporarily increases physical strength');
CALL magic_beans_schema.add_magical_property('Lightning Speed', 'Gives the ability to move at lightning speed');
CALL magic_beans_schema.add_magical_property('Healing Touch', 'Can heal minor wounds instantly');
CALL magic_beans_schema.add_magical_property('Flight', 'Grants the power of flight');
CALL magic_beans_schema.add_magical_property('Night Vision', 'Enhances vision in darkness');
CALL magic_beans_schema.add_magical_property('Shape-shifting', 'Allows the user to change appearance');
CALL magic_beans_schema.add_magical_property('Time Manipulation', 'Briefly slows or speeds up time');
CALL magic_beans_schema.add_magical_property('Telekinesis', 'Enables movement of objects with the mind');
CALL magic_beans_schema.add_magical_property('Animal Communication', 'Allows communication with animals');
CALL magic_beans_schema.add_magical_property('Earth Control', 'Manipulates the ground and stones');
CALL magic_beans_schema.add_magical_property('Wind Control', 'Gives mastery over wind currents');
CALL magic_beans_schema.add_magical_property('Fire Control', 'Allows the user to generate and control fire');
CALL magic_beans_schema.add_magical_property('Water Control', 'Grants the ability to manipulate water');
CALL magic_beans_schema.add_magical_property('Ice Control', 'Can create and manipulate ice');
CALL magic_beans_schema.add_magical_property('Illusions', 'Generates realistic illusions');
CALL magic_beans_schema.add_magical_property('Mind Reading', 'Allows the user to read thoughts');
CALL magic_beans_schema.add_magical_property('Sound Manipulation', 'Can control and alter sounds');
CALL magic_beans_schema.add_magical_property('Camouflage', 'Blends perfectly into the surroundings');
CALL magic_beans_schema.add_magical_property('Plant Growth', 'Speeds up plant growth instantly');
CALL magic_beans_schema.add_magical_property('Stone Skin', 'Temporarily turns skin into stone for defense');
CALL magic_beans_schema.add_magical_property('Poison Immunity', 'Grants resistance to all poisons');
CALL magic_beans_schema.add_magical_property('Metal Bending', 'Allows control over metal objects');
CALL magic_beans_schema.add_magical_property('Gravity Shift', 'Alters the effect of gravity');
CALL magic_beans_schema.add_magical_property('Energy Absorption', 'Absorbs energy to power abilities');
CALL magic_beans_schema.add_magical_property('Echo Location', 'Uses sound waves to navigate');
CALL magic_beans_schema.add_magical_property('Regeneration', 'Rapidly heals from injuries');
CALL magic_beans_schema.add_magical_property('Enhanced Reflexes', 'Greatly improves reaction time');
CALL magic_beans_schema.add_magical_property('Force Field', 'Creates an invisible barrier for protection');
CALL magic_beans_schema.add_magical_property('Magnetic Control', 'Manipulates magnetic fields');
CALL magic_beans_schema.add_magical_property('Dream Walking', 'Can enter and interact in others’ dreams');
CALL magic_beans_schema.add_magical_property('Shadow Step', 'Allows movement through shadows');
CALL magic_beans_schema.add_magical_property('Soul Sight', 'Can see and interact with spirits');
CALL magic_beans_schema.add_magical_property('Memory Manipulation', 'Modifies or erases memories');
CALL magic_beans_schema.add_magical_property('Luck Enhancement', 'Temporarily increases good fortune');
CALL magic_beans_schema.add_magical_property('Curse Removal', 'Lifts curses from individuals or objects');